### ISSUE TITLE
Correção Ponto 2

### ISSUE THREAD

**Issue by LucasBergholz** [Requisitos-de-Software/2023.1-VLC#111]
Ouvir o áudio do professor e realizar as correções necessárias.

**Comment by StrangeUnit28** [comment]
- [ ] Os aplicativos se adaptam as configurações do aplicativo, então acessibilidade não é um problema;
- [ ] Perfil do usuário como artefato a parte e presente na sidebar;
- [ ] Explicar dentro do perfil do usuário que o questionário foi o mesmo para elicitar requisitos e traçar o perfil do usuário;
- [ ] Especificar onde o questionário foi aplicado; 
- [ ] Talvez fazer uma análise documentar para traçar o perfil do usuário;
- [ ] Justificar os locais onde o questionário foi aplicado;
- [ ] Colocar a metodologia de criação das personas;
- [ ] Modificar os nomes das personas para nomes reais;
- [ ] Trocar o storytelling por encenação; #110 
- [ ] Na análise de documentos, dar exemplos (os principais) dos formatos de áudio e vídeo que são suportados;
- [ ] Escrever no artefato do MoSCoW quem fez o papel de quem (product owner, etc);
- [ ] A escrita dos requisitos esta errada. Tirar o "Eu como usuário...";
- [ ] Funcionalidades já implementadas são de alta prioridade.
