### ISSUE TITLE
Casos de Uso

### ISSUE THREAD

**Issue by LucasBergholz** [Requisitos-de-Software/2023.1-VLC#115]

**Comment by StrangeUnit28** [comment]
- [ ] Especificar os casos de uso;
- [ ] Os atores principais e atores secundários no diagrama de caso de uso;
- [ ] O ator principal está do lado esquerdo do sistema no diagrama de caso de uso;
- [ ] Os atores estão fora da caixa de limite do sistema no diagrama de caso de uso;
- [ ] A especificação do diagrama de caso de uso deve conter Nome, Descrição, Atores, Pré Condição, Pós Condição, Fluxo Principal, Fluxo Alternativo e Fluxo de Exceção etc.);
- [ ] A participação do cliente e/ou persona na validação do Diagrama de Casa de Uso.
